<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-17T13:50:16-04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Palmetto Dunes Oceanfront Resort',
    'version_installed' => '5.7.5.13',
    'misc' => array(
        'seen_introduction' => true,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.13',
        'user_timezones' => false,
        'access_entity_updated' => 1436997147,
    ),
    'seo' => array(
        'url_rewriting' => 1,
        'canonical_url' => 'https://www.palmettodunes.com',
        'canonical_ssl_url' => 'https://www.palmettodunes.com',
        'redirect_to_canonical_url' => 0,
        'tracking' => array(
            'code' => '<!-- Start Visual Website Optimizer Asynchronous Code -->
<script type=\'text/javascript\'>
var _vwo_code=(function(){
var account_id=130312,
settings_tolerance=2000,
library_tolerance=2500,
use_existing_jquery=false,
// DO NOT EDIT BELOW THIS LINE
f=false,d=document;return{use_existing_jquery:function(){return use_existing_jquery;},library_tolerance:function(){return library_tolerance;},finish:function(){if(!f){f=true;var a=d.getElementById(\'_vis_opt_path_hides\');if(a)a.parentNode.removeChild(a);}},finished:function(){return f;},load:function(a){var b=d.createElement(\'script\');b.src=a;b.type=\'text/javascript\';b.innerText;b.onerror=function(){_vwo_code.finish();};d.getElementsByTagName(\'head\')[0].appendChild(b);},init:function(){settings_timer=setTimeout(\'_vwo_code.finish()\',settings_tolerance);this.load(\'//dev.visualwebsiteoptimizer.com/j.php?a=\'+account_id+\'&u=\'+encodeURIComponent(d.URL)+\'&r=\'+Math.random());var a=d.createElement(\'style\'),b=\'body{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;}\',h=d.getElementsByTagName(\'head\')[0];a.setAttribute(\'id\',\'_vis_opt_path_hides\');a.setAttribute(\'type\',\'text/css\');if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(d.createTextNode(b));h.appendChild(a);return settings_timer;}};}());_vwo_settings_timer=_vwo_code.init();
</script>
<!-- End Visual Website Optimizer Asynchronous Code -->

<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,\'script\',\'//connect.facebook.net/en_US/fbevents.js\');

fbq(\'init\', \'449659138564804\');
fbq(\'track\', "PageView");
fbq(\'track\', \'Search\');
fbq(\'track\', \'Lead\');
fbq(\'track\', \'ViewContent\');</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=449659138564804&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->',
            'code_position' => 'top',
        ),
    ),
    'debug' => array(
        'detail' => 'message',
        'display_errors' => true,
    ),
    'maintenance' => array(
        'version_job_page_num' => '180',
    ),
    'cache' => array(
        'blocks' => true,
        'assets' => false,
        'theme_css' => true,
        'overrides' => true,
        'pages' => 'all',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'doctrine_dev_mode' => false,
    ),
    'theme' => array(
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ),
);
